apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-persistent-volume
  labels:
    app.kubernetes.io/name: minio-volume
    app.kubernetes.io/app: minio
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/minio/miniodata"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: minio-pv-claim
    app.kubernetes.io/app: minio
  name: minio-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: minio-db
  name: minio-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-db
    spec:
      containers:
        - env:
          - name: MINIO_REGION
            valueFrom:
              configMapKeyRef:
                key: minio_region
                name: server-env
          - name: MINIO_POSTS_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                key: minio_posts_bucket_name
                name: server-env
          - name: MINIO_PROFILES_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                key: minio_profiles_bucket_name
                name: server-env
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                key: minio_root_user
                name: credentials
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: minio_root_password
                name: credentials
          image: minio/minio:latest
          name: minio-db
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: postgres-persistent-storage
          args:
          - server
          - --console-address
          - :9001
          - /data
      restartPolicy: Always
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: minio-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: minio-db
  name: minio-db
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
    app.kubernetes.io/name: minio-db
